#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

email=$(ynh_user_get_info --username=$admin --key="mail")

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Modern team chat" --log="/var/log/$app/$app.log"

#=================================================
# ADD A CONFIGURATION
#=================================================
#ynh_script_progression "Adding $app's configuration..."

#ynh_config_add --template="some_config_file" --destination="$install_dir/some_config_file"

#chmod 400 "$install_dir/some_config_file"
#chown $app:$app "$install_dir/some_config_file"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Setup $app..."

#pushd $install_dir
#	./scripts/setup/install --postgresql-missing-dictionaries --email=$email --hostname=$domain --postgresql-version=13 --cacert="/etc/yunohost/certs/$domain/crt.pem" #--no-init-db --certbot
#popd

#pushd $install_dir
#	./scripts/setup/install --hostname=$domain --email=$email --postgresql-database-name=$db_name --postgresql-database-user=$db_user --postgresql-missing-dictionaries --self-signed-cert --no-dist-upgrade #--cacert="/etc/yunohost/certs/$domain/crt.pem"
#popd

pushd $install_dir
	./scripts/setup/install --hostname=$domain --email=$email --self-signed-cert #--postgresql-database-name=$db_name --postgresql-database-user=$db_user --postgresql-missing-dictionaries --no-dist-upgrade #--cacert="/etc/yunohost/certs/$domain/crt.pem"
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
